### ISSUE TITLE
Incorrect use of nowait in the OpenMP version of Apps_PRESSURE?

### ISSUE THREAD

**Issue by hidekisaito** [LLNL/RAJAPerf#110]
Just a theoretical problem.

The first OMP FOR loop writes to bvc[] and the second OMP FOR loop reads from it. It may work for practical purposes, but it still looks technically incorrect to me, as some threads may start executing the second loop, reading from bvc[], before some other threads finish writing to bvc[]. If there aren't good reasons to have those in two separate loops, it's better to fuse them.

It's not good to assume that the threads will execute the same iteration range for two separate OMP FOR loops.

**Comment by rhornung67** [comment]
It's  written with two loops to be representative of the application from which the kernel was pulled. We probably didn't give it much thought since the machines we run tend to have static scheduling as the default. We could specify static scheduling on both loops so that it would be guaranteed to be correct for all OpenMP implementations. Thanks for the issue.

**Comment by hidekisaito** [comment]
>We could specify static scheduling on both loops

That'll do. Sorry for being picky.
