### ISSUE TITLE
Think about how checksum should weigh elements in arrays.

### ISSUE THREAD

**Issue by MrBurmark** [LLNL/RAJAPerf#237]
Currently calcChecksum weights each element proportionally to its position relative to the start of the array. So later elements are given more weight and the total sum is proportional to the number of elements squared.
```cpp
long double tchk = 0.0;
for (Index_type j = 0; j < len; ++j) {
  tchk += (j+1)*ptr[j]*scale_factor;
}
```
I ran into issues with the checksum when implementing scan kernels with doubles as the error at each element is proportional to its position relative to the start of the array. I worked around this by setting the checksum scale factor to be inversely proportional to the problem size squared.
What do people think about changing the way we weigh elements in arrays so they are treated more equally?

**Comment by rhornung67** [comment]
I think changing the checksum calculation is a good idea. I came up with the current implementation when I started the perf suite and haven't given it much thought since. I think we should still weight the entries to avoid issues with result entries being the same but in different order. Since we run potentially much larger kernels now, the weighting gets increasingly skewed toward the later array elements as you observed. But, if all entries are near 1.0, for example, then we are potentially skewing the sum toward the earlier entries potentially when the sum gets very large. What about something like this: 

`long double tchk = 0.0;
for (Index_type j = 0; j < len; ++j) {
  tchk += std::abs( std::sin(j+1) ) * ptr[j];
}
double weight_factor = 1/1.234;
tchk *= weight_factor * scale_factor;

It would weight each entry between 0 and 1, but may not eliminate the issue I mentioned earlier.

**Comment by MrBurmark** [comment]
That makes sense that the intention is to catch permutations. We could also implement a more summation like pairwise or kahan.
I like the idea of using something like sin, but since it can get arbitrarily close to 0 maybe we should add 0.5 so nothing gets reduced too much and the sum will still be about N.
```cpp
long double tchk = 0.0;
for (Index_type j = 0; j < len; ++j) {
  tchk += (std::abs(std::sin(j+1))+0.5) * ptr[j];
}
double weight_factor = 1/1.234;
tchk *= weight_factor * scale_factor;
```

**Comment by rhornung67** [comment]
A Kahan sum would be good so that summation over many values is more accurate.

**Comment by MrBurmark** [comment]
So a final version might look something like this.
```cpp
long double tchk = 0.0;
long double ckahan = 0.0;
for (Index_type j = 0; j < len; ++j) {
  long double x = (std::abs(std::sin(j+1.0))+0.5) * ptr[j];
  long double y = x - ckahan;
  long double t = tchk + y;
  ckahan = (t - tchk) - y;
  tchk = t;
}
double weight_factor = 1/1.234;
tchk *= weight_factor * scale_factor;
```

**Comment by rhornung67** [comment]
I likey!
